services:
  hacking-db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: local
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
